<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/_User/_User.php';

    /**
     * Test class for _User.
     * Generated by PHPUnit on 2010-03-05 at 11:49:34.
     */
    class _UserTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var _User
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new _User;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testLoad().
         */
        public function testLoad ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testLoadByLogin().
         */
        public function testLoadByLogin ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetCurrent().
         */
        public function testGetCurrent ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetId().
         */
        public function testGetId ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetName().
         */
        public function testGetName ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetMail().
         */
        public function testGetMail ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetType().
         */
        public function testGetType ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testSetPass().
         */
        public function testSetPass ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetDefaultPage().
         */
        public function testGetDefaultPage ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
