<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addaccountfielddescriptions extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('account_field_descriptions', array(
             'field_description_id' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'field_visual_name' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => 150,
             ),
             'field_name' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 64,
             ),
             'field_type' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'numeric',
              1 => 'string',
              2 => 'text',
              3 => 'html',
              4 => 'enum',
              5 => 'set',
              ),
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => 7,
             ),
             'field_regexp' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'field_permissions' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => 'view',
              1 => 'select',
              2 => 'input',
              3 => 'add',
              4 => 'hidden',
              ),
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 6,
             ),
             'field_default_value' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'field_description_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('account_field_descriptions');
    }
}