<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddailycurrency extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('daily_currency', array(
             'id' => 
             array(
              'type' => 'integer',
              'autoincrement' => true,
              'primary' => true,
              'length' => 8,
             ),
             'currency_id' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'currency_from' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '1',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'currency_date' => 
             array(
              'type' => 'date',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 25,
             ),
             'currency_sum' => 
             array(
              'type' => 'decimal',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '0.0000',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 20,
              'scale' => ' 4',
             ),
             'direction' => 
             array(
              'type' => 'enum',
              'fixed' => 0,
              'unsigned' => false,
              'values' => 
              array(
              0 => '+',
              1 => '-',
              2 => '0',
              ),
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'currency_user_sum' => 
             array(
              'type' => 'decimal',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '0.0000',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 20,
              'scale' => ' 4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '0',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('daily_currency');
    }
}