<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addoperation extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('operation', array(
             'id' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'user_id' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'money' =>
             array(
              'type' => 'decimal',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 20,
              'scale' => ' 2',
             ),
             'time' =>
             array(
              'type' => 'time',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 25,
             ),
             'date' =>
             array(
              'type' => 'date',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => '0000-00-00',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 25,
             ),
             'cat_id' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '0',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'account_id' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '0',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'drain' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '1',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'comment' =>
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'transfer' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '0',
              'notnull' => false,
              'autoincrement' => false,
              'length' => 4,
             ),
             'tr_id' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => 8,
             ),
             'imp_id' =>
             array(
              'type' => 'decimal',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => 20,
              'scale' => ' 2',
             ),
             'tags' =>
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => 255,
             ),
             'type' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '0',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'source_id' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '1',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 4,
             ),
             'accepted' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '1',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 1,
             ),
             'chain_id' =>
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 8,
             ),
             'exchange_rate' =>
             array(
              'type' => 'decimal',
              'fixed' => 0,
              'unsigned' => true,
              'primary' => false,
              'default' => '0.0000',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 10,
              'scale' => ' 6',
             ),
             'dt_create' =>
             array(
              'type' => 'timestamp',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 25,
             ),
             'dt_update' =>
             array(
              'type' => 'timestamp',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 25,
             ),
             ), array(
             'indexes' =>
                 array(
                    'account_id' => array('fields' => 'account_id'),
                    'user_id'    => array('fields' => 'user_id'),
                 ),
                 'primary' =>
                 array(
                  0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('operation');
    }
}
