<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/Article/Article.php';

    /**
     * Test class for Article.
     * Generated by PHPUnit on 2010-03-05 at 11:49:38.
     */
    class ArticleTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var Article
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new Article;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testLoad().
         */
        public function testLoad ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testEdit().
         */
        public function testEdit ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDelete().
         */
        public function testDelete ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testCreate().
         */
        public function testCreate ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetId().
         */
        public function testGetId ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetTitle().
         */
        public function testGetTitle ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testSetTitle().
         */
        public function testSetTitle ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetDate().
         */
        public function testGetDate ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetAnnounce().
         */
        public function testGetAnnounce ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testSetAnnounce().
         */
        public function testSetAnnounce ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetBody().
         */
        public function testGetBody ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetAuthorName().
         */
        public function testGetAuthorName ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetAuthorUrl().
         */
        public function testGetAuthorUrl ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetArray().
         */
        public function testGetArray ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
