# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App


prod:
  easybank:
    mailCardCiti: [devel_test@easyfinance.ru, prod_copy@easyfinance.ru]

  # Данные для подключения робокассы
  billing:
    robokassa:
      scriptUrl:            https://merchant.roboxchange.com/Handler/MrchSumPreview.ashx
      url:                  https://merchant.roboxchange.com/Index.aspx
      login:                easyfinance
      pass1:                Hud^y&6e35$resDf # Пароль 1
      pass2:                gdYdt63Gsldbe5!d # Пароль 2

all:
  easybank:
    mailCardCiti: devel_test@easyfinance.ru

  # Данные для подключения робокассы
  billing:
    robokassa:
      scriptUrl:            https://merchant.roboxchange.com/Handler/MrchSumPreview.ashx
      url:                  http://test.robokassa.ru/Index.aspx
      login:                easyfinance_test
      pass1:                test123456789 # Пароль 1
      pass2:                test987654321 # Пароль 2
  # Операции, созданные в какой период, считаются "будущими" операциями в календаре
  calendarFuture:
      daysStart:            1 # От 1 дня
      daysEnd:              8 # До 8 дней

  # Категории
  categories:
    recent:
      limit: 10         # максимальное кол-во часто используемых категорий
      operationsFor: 3  # кол-во операций по категории, для попадания в частые
