
# сохранение запланированной операции
calendar_add:
  url: /calendar/add
  class: sfRoute
  param: { module: calendar, action: add }
  requirements:
    sf_method: [get, post]

# сохранение настроек оповещений, t1497
save_reminder_settings:
  url: /profile/save_reminders
  class: sfRoute
  param: { module: profile, action: saveReminders }
  requirements:
    sf_method: [get, post]

# загрузка пользовательских данных в js-объект
load_user_data:
  url: /profile/load_main_settings
  class: sfRoute
  param: { module: profile, action: loadUserData }

# Создать счет
pda_account_create:
  url:      /account.pda
  class:    sfDoctrineRoute
  options:  { model: Account, type: object }
  param:    { module: account, action: createForPda, sf_format: pda }
  requirements:
    sf_method: post

account_create:
  url:      /account.:sf_format
  class:    sfDoctrineRoute
  options:  { model: Account, type: object }
  param:    { module: account, action: create }
  requirements:
    sf_method: post

# Редактировать счет
account_edit:
  url:      /accountedit/:id.:sf_format
  class:    sfDoctrineRoute
  options:  { model: Account, type: object }
  param:    { module: account, action: edit }
  requirements:
    sf_method: post

# default rules
homepage:
  url:   /
  params: { module: info, action: index }

services:
  url:   /services/
  params: { module: services, action: index }

robokassa:
  url:   /robokassa/:action
  params: { module: robokassa }
