
# Создать счет
pda_account_create:
  url:      /account.pda
  class:    sfDoctrineRoute
  options:  { model: Account, type: object }
  param:    { module: account, action: createForPda, sf_format: pda }
  requirements:
    sf_method: post

account_create:
  url:      /account.:sf_format
  class:    sfDoctrineRoute
  options:  { model: Account, type: object }
  param:    { module: account, action: create }
  requirements:
    sf_method: post


# default rules
homepage:
  url:   /
  params: { module: info, action: index }

services:
  url:   /services
  params: { module: services, action: index }

robokassa:
  url:   /robokassa/:action
  params: { module: robokassa }