
# Создать счет
account_create:
  url:      /account.:sf_format
  class:    sfDoctrineRoute
  options:  { model: Account, type: object }
  param:    { module: account, action: create }
  requirements:
    sf_method: post

# default rules
homepage:
  url:   /
  param: { module: info, action: index }
