# Временная заглушка
homepage:
  url:   /
  params: { module: info, action: index }


# Профиль
# ------------------------------------------------------------------------------

# отобразить форму редактирования профиля
profile_form:
  url:   /profile/
  class: sfRoute
  param: { module: profile, action: index }
  requirements:
    sf_method: [get]

# сохранение профиля
profile_save:
  url:   /profile/save_main_settings.:sf_format
  class: sfRequestRoute
  param: { module: profile, action: save }
  requirements:
    sf_method: [post] # PUT, если js-кой эмулировать =)
    sf_format: json

# сохранение настроек оповещений, t1497
save_reminder_settings:
  url: /profile/save_reminders
  class: sfRoute
  param: { module: profile, action: saveReminders }
  requirements:
    sf_method: [get, post]

# загрузка пользовательских данных в js-объект
load_user_data:
  url: /profile/load_main_settings
  class: sfRoute
  param: { module: profile, action: loadUserData }


# Счета
# ------------------------------------------------------------------------------

# Создать счет для PDA, TODO: убрать в отдельное app
pda_account_create:
  url:      /account.pda
  class:    sfDoctrineRoute
  options:  { model: Account, type: object }
  param:    { module: account, action: createForPda, sf_format: pda }
  requirements:
    sf_method: post

# Создать счет
account_create:
  url:      /account.:sf_format
  class:    sfDoctrineRoute
  options:  { model: Account, type: object }
  param:    { module: account, action: create }
  requirements:
    sf_method: post

# Редактировать счет
account_edit:
  url:      /accountedit/:id.:sf_format
  class:    sfDoctrineRoute
  options:  { model: Account, type: object }
  param:    { module: account, action: edit }
  requirements:
    sf_method: post


# Услуги
# ------------------------------------------------------------------------------

services:
  url:   /services/
  params: { module: services, action: index }

robokassa:
  url:   /robokassa/:action
  params: { module: robokassa }

# Обёртка для wiki
# ------------------------------------------------------------------------------

wikiwrapper:
  url:    /wikiwrapper/
  class:  sfRoute
  params: { module: wikiwrapper, action: index }

wikiwrapper_page:
  url:    /wikiwrapper/:wikiURL
  class:  sfRoute
  params: { module: wikiwrapper, action: index }
  requirements:
    wikiURL: \S+

# Статические страницы
# ------------------------------------------------------------------------------

page_review:
  url:    /review/
  class:  sfRoute
  params: { module: page, action: index, pageName: review }


page:
  url:    /page/:pageName
  class:  sfRoute
  params: { module: page, action: index }
  requirements:
    pageName: \S+
