# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            8bffedc17450d19df5ccb604944c8410afd7ec28

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    # Cache settings
    lazy_cache_key:          true # Delays creation of a cache key until after checking whether an action or partial is cacheable

    # Charset used for the response
    charset:                 utf-8

    # Routing settings
    no_script_name:          true # Enable the front controller name in generated URLs

    # Helpers included in all templates by default
    standard_helpers:       [Partial,Cache,I18N]

    # i18n
    i18n:                   false # Enable interface translation. Set to false if your application should not be translated.
    default_culture:        ru

  .actions:
    login_module:           ~
    login_action:           ~

    secure_module:          ~
    secure_action:          ~
