# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         Easyfinance.ru - домашняя бухгалтерия, личный бюджет и финансы
    #description:  symfony project
    #keywords:     symfony, project
    language:      ru
    #robots:       index, follow

<?php if (sfConfig::get('sf_environment') == 'prod'): ?>
  stylesheets:    [global-min.css?r=<?php echo REVISION; ?>]
  javascripts:    [global-min.js?r=<?php echo REVISION; ?>]
<?php else: ?>
  stylesheets:
<?php
    foreach (file(sfConfig::get('sf_root_dir') . '/../include/assets/css.list') as $css) {
        echo "    - ", $css, "\n";
    }
?>
  javascripts:
<?php
    foreach (file(sfConfig::get('sf_root_dir') . '/../include/assets/js.list') as $js) {
        echo "    - ", $js, "\n";
    }
?>
<?php endif; ?>

  has_layout:     true
  layout:         layout
