<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/Certificate/Model.php';

    /**
     * Test class for Certificate_Model.
     * Generated by PHPUnit on 2010-03-05 at 11:49:31.
     */
    class Certificate_ModelTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var Certificate_Model
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new Certificate_Model;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testLoadByUserId().
         */
        public function testLoadByUserId ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testCreate().
         */
        public function testCreate ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDelete().
         */
        public function testDelete ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement test__get().
         */
        public function test__get ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
