
all:

  # Уведомления об операциях
  notification:

    max_errors: 5
    ttl:        86400  # сек, в течение какого срока, уведомление актуально

    # Параметры SMS-шлюза
    sms_url:   http://www.websms.ru/http_in5.asp
    sms_login: easyfinance
    sms_pass:  asdgh124367ASGJ

    # Уведомления по Email
    email_from: reminder@easyfinance.ru
    email_name: EasyFinance Reminder


  # Импорт операций (СИТИ)
  emailImport:
    subject:        "EasyFinance.ru - Fwd: "
    from:           "helpdesk@easyfinance.ru"
    fromName:       "EasyFinance.ru"
