
test:
  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

prod:
  mailer:
    param:
      delivery_strategy: realtime
      transport:
        class: Swift_SendmailTransport
        param:
          command: /usr/sbin/sendmail -bs

all:
  mailer:
    class: sfMailer
    param:
      delivery_strategy: realtime
      transport:
        class: Swift_MailTransport
