<?php
//define('INDEX',true);
require_once 'PHPUnit/Framework.php';
require_once 'C:\WebServers\home\hm\core\core.class.php';

/**
 * Test class for Core.
 * Generated by PHPUnit on 2009-09-12 at 12:31:29.
 */
class CoreTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Core
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = Core::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
        $this->object = NULL;
    }

    /**
     * @todo Implement testGetInstance().
     */
    public function testGetInstance()
    {
        $this->assertNotEquals(NULL, $this->object->getInstance());
        //$this->assertEquals(8, 8);
    }

    /**
     * @todo Implement testParseUrl().
     */
    public function testParseUrl()
    {
        // Remove the following lines when you implement this test.
        $this->assertEquals(8, 8);
    }

    /**
     * @todo Implement testAuthUser().
     */
    public function testAuthUser()
    {
        //$this->assertNotEquals(NULL, $this->object->authUser());
        //$this->assertNotEquals(123, $this->object->authUser());
    }
}
?>
