<?php
//ini_set("include_path", dirname(dirname(dirname(__FILE__))).PATH_SEPARATOR.ini_get("include_path"));
define('INDEX', true);
require_once 'PHPUnit/Framework.php';
require_once 'include/functions.php';
require_once 'core.class.php';

/**
 * Test class for Core.
 * Generated by PHPUnit on 2009-09-12 at 12:31:29.
 */
class CoreTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Core
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Core;
        $this->assertEquals(8, 8);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
        $this->assertEquals(8, 8);
    }

    /**
     * @todo Implement testGetInstance().
     */
    public function testGetInstance()
    {
        $this->assertEquals(8, 8);
    }

    /**
     * @todo Implement testParseUrl().
     */
    public function testParseUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAuthUser().
     */
    public function testAuthUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
