<?php
ini_set("include_path", "../core".PATH_SEPARATOR."../../core".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once 'user.class.php';

/**
 * Test class for User.
 * Generated by PHPUnit on 2009-09-12 at 13:00:40.
 */
class UserTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    User
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
        $this->object = NULL;
    }

    /**
     * @todo Implement testInit().
     */
    public function testInit()
    {
        $this->assertNotEquals(NULL, $this->object->Init(1));
    }

//    /**
//     * @todo Implement testGetId().
//     */
//    public function testGetId()
//    {
//
//    }
//
//    /**
//     * @todo Implement testInitUser().
//     */
//    public function testInitUser()
//    {
//
//    }
//
//    /**
//     * @todo Implement testSave().
//     */
//    public function testSave()
//    {
//
//    }
//
//
//    /**
//     * @todo Implement testDestroy().
//     */
//    public function testDestroy()
//    {
//
//    }
//
//    /**
//     * @todo Implement testLoad().
//     */
//    public function testLoad()
//    {
//
//    }
//
//    /**
//     * @todo Implement testInitUserCategory().
//     */
//    public function testInitUserCategory()
//    {
//
//    }
//
//    /**
//     * @todo Implement testInitUserCurrency().
//     */
//    public function testInitUserCurrency()
//    {
//
//    }
//
//    /**
//     * @todo Implement testInitUserAccounts().
//     */
//    public function testInitUserAccounts()
//    {
//
//    }
//
//    /**
//     * @todo Implement testGetProfile().
//     */
//    public function testGetProfile()
//    {
//
//    }
//
//    /**
//     * @todo Implement testUpdateProfile().
//     */
//    public function testUpdateProfile()
//    {
//
//    }
//
//    /**
//     * @todo Implement testGetUserCategory().
//     */
//    public function testGetUserCategory()
//    {
//
//    }
//
//    /**
//     * @todo Implement testGetUserCurrency().
//     */
//    public function testGetUserCurrency()
//    {
//
//    }
//
//    /**
//     * @todo Implement testGetUserAccounts().
//     */
//    public function testGetUserAccounts()
//    {
//
//    }
//
//    /**
//     * @todo Implement testGetUserProps().
//     */
//    public function testGetUserProps()
//    {
//
//    }
}
?>