<?php
$xmlRequest='<?xml version="1.0" encoding="UTF-8"?>
<methodCall>
    <methodName>sync.getAuth</methodName>
    <params>
        <param>
        <value>
            <struct>
                <member>
                    <name>type</name>
                    <value>service</value>
                </member>
                <member>
                    <name>name</name>
                    <value>auth</value>
                </member>
                <member>
                    <name>login</name>
                    <value>PrinceOfPersia</value>
                </member>
                <member>
                    <name>pass</name>
                    <value>b1b3773a05c0ed0176787a4f1574ff0075f7521e</value>
                </member>
                <member>
                    <name>lastsync</name>
                    <value>20091003T10:11:12
                    </value>
                </member>
                <member>
                    <name>digsignature</name>
                    <value>n2jdy303yeer7j2v</value>
                </member>
            </struct>
        </value>
        </param>

        <param>
        <value>
            <array>
                <data>
                    <value>
                        <struct>
                            <member>
                                <name>type</name>
                               <value>service</value>
                            </member>
                            <member>
                                <name>name</name>
                                <value>RecordsMap</value>
                            </member>
                        </struct>
                    </value>
                    

  </data>
</array>
</value>


   </param>

   <param>

<value>
  <array>
    <data>
<value>
  <struct>
    <member>
      <name>tablename</name>
      <value><string>Categories</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>CL_1</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>0</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Петров</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>0</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>DL_1</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>0</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Петров</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>0</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>DL_2</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>0</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Смирнов</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>0</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>CE_5</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>0</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Машина</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>CE_1</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>0</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Продукты</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>CE_6</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>0</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Развлечение</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>CE_2</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>0</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Транспорт</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>CI_4</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>0</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Заработок</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>CI_1</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>0</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Зарплата</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SE_8</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CE_5</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Бензин</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SE_1</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CE_1</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Колбаса</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SE_2</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CE_1</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Масло</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SE_3</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CE_1</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Хлеб</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SE_10</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CE_6</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Кино</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SE_4</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CE_2</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Автобус</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SE_5</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CE_2</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Метро</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>-1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SI_7</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CI_4</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Зарплата</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SI_1</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CI_1</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Аванс</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>1</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>SI_2</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CI_1</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Премия</string></value>
    </member>
    <member>
      <name>type</name>
      <value><string>1</string></value>
    </member>
  </struct>
</value>

  </data>
</array>
</value>


   </param>

   <param>

<value>
  <array>
    <data>
<value>
  <struct>
    <member>
      <name>tablename</name>
      <value><string>Accounts</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>RUR_</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Кошелек(RUR)</string></value>
    </member>
    <member>
      <name>cur</name>
      <value><int>1</int></value>
    </member>
    <member>
      <name>date</name>
      <value><string>01.08.2007</string></value>
    </member>
    <member>
      <name>startbalance</name>
      <value><double>3000</double></value>
    </member>
    <member>
      <name>descr</name>
      <value><string></string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>RUR_1</string></value>
    </member>
    <member>
      <name>name</name>
      <value><string>Служебный(RUR)</string></value>
    </member>
    <member>
      <name>cur</name>
      <value><int>1</int></value>
    </member>
    <member>
      <name>date</name>
      <value><string>01.10.2009</string></value>
    </member>
    <member>
      <name>startbalance</name>
      <value><double>100</double></value>
    </member>
    <member>
      <name>descr</name>
      <value><string></string></value>
    </member>
  </struct>
</value>

  </data>
</array>
</value>


   </param>

   <param>

<value>
  <array>
    <data>
<value>
  <struct>
    <member>
      <name>tablename</name>
      <value><string>Incomes</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>I_1</string></value>
    </member>
    <member>
      <name>date</name>
      <value><string>17.10.2009</string></value>
    </member>
    <member>
      <name>category</name>
      <value><string>SI_0</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CI_1</string></value>
    </member>
    <member>
      <name>account</name>
      <value><string>RUR_0</string></value>
    </member>
    <member>
      <name>amount</name>
      <value><double>5000</double></value>
    </member>
    <member>
      <name>descr</name>
      <value><string></string></value>
    </member>
  </struct>
</value>

  </data>
</array>
</value>


   </param>

   <param>

<value>
  <array>
    <data>
<value>
  <struct>
    <member>
      <name>tablename</name>
      <value><string>Outcomes</string></value>
    </member>
  </struct>
</value>

<value>
  <struct>
    <member>
      <name>kkey</name>
      <value><string>E_1</string></value>
    </member>
    <member>
      <name>date</name>
      <value><string>17.10.2009</string></value>
    </member>
    <member>
      <name>category</name>
      <value><string>SE_0</string></value>
    </member>
    <member>
      <name>parent</name>
      <value><string>CE_1</string></value>
    </member>
    <member>
      <name>account</name>
      <value><string>RUR_0</string></value>
    </member>
    <member>
      <name>amount</name>
      <value><double>10</double></value>
    </member>
    <member>
      <name>descr</name>
      <value><string></string></value>
    </member>
  </struct>
</value>

  </data>
</array>
</value>


   </param>

   </params>

</methodCall>';
