
# Sync: Авторизация
auth:
  url: /login.:sf_format
  class:   sfRequestRoute
  params:  { module: auth, action: login, sf_format: xml }
  requirements:
    sf_method: post
    sf_format: xml

# Sync: Отдать список измененных объектов
sync_get_modified:
  url: /modified/:model.:sf_format
  class:   sfRequestRoute
  params:  { module: sync, action: syncOut, sf_format: xml }
  requirements:
    sf_method: get
    sf_format: xml

# Sync: Отдать бюджет на текущий месяц
sync_get_budget:
  url: /budget.:sf_format
  class:   sfRequestRoute
  params:  { module: sync, action: syncOutBudget, sf_format: xml }
  requirements:
    sf_method: get
    sf_format: xml

# Sync(In): Принять набор счетов
sync_in_account:
  url: /update/account.:sf_format
  class:   sfRequestRoute
  params:  { module: sync, action: syncInAccount, sf_format: xml }
  requirements:
    sf_method: post
    sf_format: xml

# Sync(In): Принять набор категорий
sync_in_category:
  url: /update/category.:sf_format
  class:   sfRequestRoute
  params:  { module: sync, action: syncInCategory, sf_format: xml }
  requirements:
    sf_method: post
    sf_format: xml

# Sync(In): Принять набор операций
sync_in_operation:
  url: /update/operation.:sf_format
  class:   sfRequestRoute
  params:  { module: sync, action: syncInOperation, sf_format: xml }
  requirements:
    sf_method: post
    sf_format: xml
