
# Sync: Отдать список измененных объектов
sync_get_modified:
  url: /modified/:model.:sf_format
  class:   sfRequestRoute
  params:  { module: sync, action: syncOut, sf_format: xml }
  requirements:
    sf_method: get

# Sync(In): Принять набор счетов
sync_in_account:
  url: /post/accounts.:sf_format
  class:   sfRequestRoute
  params:  { module: sync, action: syncInAccount, sf_format: xml }
  requirements:
    sf_method: post

# Sync(In): Принять набор категорий
sync_in_category:
  url: /post/category.:sf_format
  class:   sfRequestRoute
  params:  { module: sync, action: syncInCategory, sf_format: xml }
  requirements:
    sf_method: post
