all:
  myAuth:
    registerRoutes: true  # подключать роуты плагина для авторизации
    rememberMe:     true  # запоминать пользователя
    rememberMeDuration: 1296000 # запоминать на n секунд
    rememberMe_cookie:  myAuthRememberMe # название запоминательной куки
