<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../../classes/_Core/TemplateEngine/TemplateEngine.php';

    /**
     * Test class for _Core_TemplateEngine.
     * Generated by PHPUnit on 2010-03-05 at 11:49:46.
     */
    class _Core_TemplateEngineTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var _Core_TemplateEngine
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new _Core_TemplateEngine;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testGetPrepared().
         */
        public function testGetPrepared ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetResponseMode().
         */
        public function testGetResponseMode ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
