<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../../classes/_Core/TemplateEngine/Json.php';

    /**
     * Test class for _Core_TemplateEngine_Json.
     * Generated by PHPUnit on 2010-03-05 at 11:49:46.
     */
    class _Core_TemplateEngine_JsonTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var _Core_TemplateEngine_Json
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new _Core_TemplateEngine_Json;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testAssign().
         */
        public function testAssign ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testExcludeFromOutput().
         */
        public function testExcludeFromOutput ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testAppend().
         */
        public function testAppend ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDisplay().
         */
        public function testDisplay ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
