<?php

/**
 * myDoctrineLoggerEventTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class myDoctrineLoggerEventTable extends PluginmyDoctrineLoggerEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object myDoctrineLoggerEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('myDoctrineLoggerEvent');
    }
}