<?php

/**
 * myDoctrineLoggerEvent
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    EasyFinance
 * @subpackage model
 * @author     EasyFinance
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class myDoctrineLoggerEvent extends PluginmyDoctrineLoggerEvent
{
}
