<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/Sync/SyncOperationModel.php';

    /**
     * Test class for SyncOperation_Model.
     * Generated by PHPUnit on 2010-03-05 at 11:49:42.
     */
    class SyncOperation_ModelTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var SyncOperation_Model
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new SyncOperation_Model;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testAddOperation().
         */
        public function testAddOperation ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testEditOperation().
         */
        public function testEditOperation ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDeleteOperation().
         */
        public function testDeleteOperation ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testFormOperation().
         */
        public function testFormOperation ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
