<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/Sync/SyncTransferModel.php';

    /**
     * Test class for SyncTransfer_Model.
     * Generated by PHPUnit on 2010-03-05 at 11:49:41.
     */
    class SyncTransfer_ModelTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var SyncTransfer_Model
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new SyncTransfer_Model;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testAddTransfer().
         */
        public function testAddTransfer ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testEditTransfer().
         */
        public function testEditTransfer ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDeleteTransfer().
         */
        public function testDeleteTransfer ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testFormTransfer().
         */
        public function testFormTransfer ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
