<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/Sync/Sync.php';

    /**
     * Test class for Sync.
     * Generated by PHPUnit on 2010-03-05 at 11:49:42.
     */
    class SyncTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var Sync
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new Sync;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testCleanRec().
         */
        public function testCleanRec ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testClearAll().
         */
        public function testClearAll ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDeleteAllByUser().
         */
        public function testDeleteAllByUser ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDeleteRecMapByUser().
         */
        public function testDeleteRecMapByUser ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetDate().
         */
        public function testGetDate ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testWriteDataAndAnswerRec().
         */
        public function testWriteDataAndAnswerRec ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testQwe().
         */
        public function testQwe ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testSync_getAuth().
         */
        public function testSync_getAuth ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testSendError().
         */
        public function testSendError ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testParsing().
         */
        public function testParsing ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetRecordsMap().
         */
        public function testGetRecordsMap ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetChangedRecords().
         */
        public function testGetChangedRecords ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetDeletedRecords().
         */
        public function testGetDeletedRecords ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetAccounts().
         */
        public function testGetAccounts ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetTransfers().
         */
        public function testGetTransfers ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetCategories().
         */
        public function testGetCategories ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetCurrensies().
         */
        public function testGetCurrensies ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetDebets().
         */
        public function testGetDebets ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetIncomes().
         */
        public function testGetIncomes ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetOutcomes().
         */
        public function testGetOutcomes ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testGetPlans().
         */
        public function testGetPlans ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testWriteTest().
         */
        public function testWriteTest ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
