<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/Sync/SyncCategoryModel.php';

    /**
     * Test class for SyncCategory_Model.
     * Generated by PHPUnit on 2010-03-05 at 11:49:43.
     */
    class SyncCategory_ModelTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var SyncCategory_Model
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new SyncCategory_Model;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testAddCategory().
         */
        public function testAddCategory ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testEditCategory().
         */
        public function testEditCategory ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDeleteCategory().
         */
        public function testDeleteCategory ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testFormCategory().
         */
        public function testFormCategory ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
