<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/Sync/SyncPeriodicModel.php';

    /**
     * Test class for SyncPeriodic_Model.
     * Generated by PHPUnit on 2010-03-05 at 11:49:41.
     */
    class SyncPeriodic_ModelTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var SyncPeriodic_Model
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new SyncPeriodic_Model;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testAddPeriodic().
         */
        public function testAddPeriodic ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testEditPeriodic().
         */
        public function testEditPeriodic ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDeletePeriodic().
         */
        public function testDeletePeriodic ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testFormPeriodic().
         */
        public function testFormPeriodic ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
