<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/Account/Exception.php';

    /**
     * Test class for Account_Exception.
     * Generated by PHPUnit on 2010-03-05 at 11:49:28.
     */
    class Account_ExceptionTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var Account_Exception
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new Account_Exception;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }
    }

?>
