<?php

/**
 * PluginmyAuthRememberKeyTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyAuthRememberKeyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyAuthRememberKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyAuthRememberKey');
    }
}