<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../../classes/Sync/RecordsMap/RecordsMapModel.php';

    /**
     * Test class for RecordsMap_Model.
     * Generated by PHPUnit on 2010-03-05 at 11:49:47.
     */
    class RecordsMap_ModelTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var RecordsMap_Model
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new RecordsMap_Model;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testAddRecordsMapString().
         */
        public function testAddRecordsMapString ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testDelRecordsMapString().
         */
        public function testDelRecordsMapString ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testWriteRecMap().
         */
        public function testWriteRecMap ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testFormRecordsMap().
         */
        public function testFormRecordsMap ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
