# главная страница админки
homepage:
  url:   /
  param: { module: sfAdminDash, action: dashboard }


email_parser:
  class: sfDoctrineRouteCollection
  options:
    model:                EmailParser
    module:               emailparsers
    prefix_path:          /emailparsers
    column:               id
    with_wildcard_routes: true

email_source:
  class: sfDoctrineRouteCollection
  options:
    model:                EmailSource
    module:               emailsources
    prefix_path:          /emailsources
    column:               id
    with_wildcard_routes: true

service_subscription:
  class: sfDoctrineRouteCollection
  options:
    model:                ServiceSubscription
    module:               subscriptions
    prefix_path:          /subscriptions
    column:               id
    with_wildcard_routes: true

service:
  class: sfDoctrineRouteCollection
  options:
    model:                Service
    module:               services
    prefix_path:          /services
    column:               id
    with_wildcard_routes: true

billing_transaction:
  class: sfDoctrineRouteCollection
  options:
    model:                BillingTransaction
    module:               transactions
    prefix_path:          /transactions
    column:               id
    with_wildcard_routes: true

my_doctrine_logger_event:
  class: sfDoctrineRouteCollection
  options:
    model:                myDoctrineLoggerEvent
    module:               myDoctrineLoggerEvent
    prefix_path:          /my_doctrine_logger_event
    column:               id
    with_wildcard_routes: true
