generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ServiceSubscription
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          service_subscription
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id:                  { label: "ID" }
        user_name:           { label: "Пользователь" }
        service_link:        { label: "Услуга" }
        created_at:          { label: "Дата начала действия услуги",  date_format: dd.MM.yyyy }
        subscribed_till:     { label: "Дата окончания действия услуги",  date_format: dd.MM.yyyy }
      list:    
        title: Список подписок
        sort: [subscribed_till, asc]
        display: [ id, _user_name, _service_link, created_at, subscribed_till]
        actions: []
      filter:
        fields:
          user_id:           { label: "Пользователь" }
          service_id:        { label: "Услуга" }
          subscribed_till:        { label: "Дата окончания действия услуги",  date_format: dd.MM.yyyy }
          created_at:          { label: "Дата начала действия услуги",  date_format: dd.MM.yyyy }        
        display: [user_id, service_id, created_at, subscribed_till]
      form:    ~
      edit:
        title: Изменение подписки пользователя %%user_name%% на услугу "%%service_name%%"    
        fields:
          subscribed_till:        { label: "Дата окончания действия услуги",  date_format: dd.MM.yyyy }
        display: [subscribed_till]
      new:     ~
