# (!) Схема не покрывает полностью БД
# Напротив каждой таблицы указывается % покрытия,
# например: "100% - OK"
#
# Оставшиеся таблицы:
#
#Acc_ConnectionTypes
#Acc_Fields
#Acc_Object
#account_field_descriptions
#account_field_values
#account_fields
#articles
#budget
#calend
#calendar_chains
#calendar_events
#daily_currency
#logs
#feedback_message
#images
#images_articles
#messages
#messages_state
#referrers
#registration
#tags



options:
  type: INNODB
  charset: utf8

# Валюта (8/10 - PART)
# Пропущено:
#   - cur_okv_id
#   - cur_country
Currency:
  tableName: currency
  actAs: [Timestampable]
  columns:
    id:          { name: cur_id as id,           type: integer(4),  notnull: true, primary: true, autoincrement: true }
    code:        { name: cur_char_code as code,  type: string(15),  notnull: true }
    symbol:      { name: cur_name as symbol,     type: string(10),  notnull: true }
    name:        { name: cur_name_value as name, type: string(255), notnull: true }
    rate:        {                               type: 'decimal(20, 6)', notnull: true, default: 1 }
    is_active:   { name: cur_uses as is_active,  type: integer(1),  notnull: true, unsigned: true, default: 0 }
  options:
    symfony:
      form:  false
      filter: false


# Пользователи системы
User:
  tableName: users
  columns:
    id:                { type: integer(4), unsigned: true, notnull: true, primary: true, autoincrement: true }
    user_name:
      type: string
      size: 100
      notnull: true
      name: user_name as name
    user_service_mail: { type: string(100), notnull: true }
    currency_id:       { name: user_currency_default as currency_id, type: integer(4), notnull: true, default: 1 }
  options:
    symfony:
      form:  false
      filter: false


# Тип счёта (100% - ОК)
AccountType:
  tableName: account_types
  columns:
    account_type_id:   { type: integer(4), notnull: true, unsigned: true, primary: true, autoincrement: true }
    account_type_name: { type: string(255) }
  options:
    symfony:
      form:  false
      filter: false


# Счет (100% - OK)
Account:
  tableName: accounts
  actAs: [Timestampable, SoftDelete]
  columns:
    id:          { name: account_id as id,                   type: integer(4),  notnull: true, primary: true, autoincrement: true }
    user_id:     {                                           type: integer(4),  notnull: true, unsigned: true }
    type_id:     { name: account_type_id as type_id,         type: integer(4),  notnull: true }
    currency_id: { name: account_currency_id as currency_id, type: integer(4),  notnull: true }
    name:        { name: account_name as name,               type: string(255), notnull: true }
    description: { name: account_description as description, type: string(255), notnull: true }
  relations:
    User:
      local: user_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Accounts      # User->Accounts
    Currency:
      local: currency_id
      foreign: id
      type: one
      foreignType: many
      autoComplete: false         # Currency ничего не узнает
    AccountType:
      local: account_type_id
      foreign: account_type_id
      type: one
      foreignType: many
      autoComplete: false         # AccountType ничего не узнает
  options:
    symfony:
      filter: false


# Свойство счета  (100% - OK)
AccountProperty:
  tableName: Acc_Values
  columns:
    id:          { type: integer(4), notnull: true, unsigned: true, primary: true, autoincrement: true }
    account_id:  { type: integer(4), notnull: true, unsigned: true }
    field_id:    { type: integer(4), notnull: true, unsigned: true }
    field_value: { type: string(255) }
  relations:
    Account:
      local:   account_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Properties    # Account->Properties
  options:
    symfony:
      form:  false
      filter: false


# Операция с деньгами (16/21 - PART)
# Пропущено:
#   - time
#   - tr_id
#   - tags
#   - source_id
#   - exchange_rate
Operation:
  tableName: operation
  actAs: [Timestampable, SoftDelete]
  columns:
    user_id:     { type: integer(4), unsigned: true, notnull: true }
    account_id:  { type: integer(4), unsigned: true, default: null}             # ID счёта
    category_id: { name: cat_id as category_id, type: integer(4), default: null, unsigned: true} # ID категории
    amount:      { name: money as amount, type: 'decimal(20, 2)', notnull: true ,unsigned: true} # Сумма
    date:        { type: date(25), notnull: true }                               # Фактическа дата операции
    drain:       { type: integer(1), unsigned: true, notnull: true, default: 1 } # @deprecated, тип операции
    type:        { type: integer(1), unsigned: true, notnull: true, default: 0 } # Тип операции: приход, расход, перевод
    comment:     { type: clob }
    source_id:   { type: string(8), fixed: true }                                # Тип внешнего источника операции
    accepted:    { type: integer(1), unsigned: true, notnull: true, default: 1 } # Да/Нет - черновик
    transfer_account_id: { name: transfer as transfer_account_id, type: integer(4),       notnull: false, default: null } # ID счета получателя
    transfer_amount:     { name: imp_id as transfer_amount,       type: 'decimal(20, 2)', notnull: false, default: null } # Сумма счета получателя
    chain_id:    { type: integer(4), notnull: false, default: null }             # Связь с календарем
  relations:
    User:
      local: user_id
      foreign: id
      type: one
      foreignType: many
      autoComplete: false         # User ничего не узнает
    Account:
      local: account_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Operations    # Account -> Operations
    Category:
      local: category_id
      foreign: id
      type: one
      foreignType: many
      autoComplete: false         # Category ничего не узнает
  indexes:
    user_id:    { fields: [user_id] }
  options:
    symfony:
      form:  false
      filter: false


# Операция из внешнего источника (100% - OK)
SourceOperation:
  tableName: source_operations
  columns:
    operation_id:         { type: integer,    notnull: true, primary: true }
    source_uid:           { type: string(8),  notnull: true, fixed: true }
    source_operation_uid: { type: string(32), notnull: true }
  relations:
    Operation:
      local: operation_id
      foreign: id
      type: one
      foreignType: one
      onDelete: CASCADE      # При удалении операции удаляются вся информация об источнике
  indexes:
    source_operation:
      fields: [source_uid, source_operation_uid]
      type: unique
  options:
    symfony:
      form:  false
      filter: false

# Услуги биллинга
Service:
  actAs: [Timestampable]
  tableName: billing_services
  columns:
    id:                     { type: integer(4),    unsigned: true, primary: true,  autoincrement: true }   # ID услуги
    name:                   { type: string(64), notnull: true }                                         # Наименование услуги
    price:                  { type: float,      unsigned: true, notnull: true }                         # Стоимость услуги
  options:
    symfony:
      form:  true
      filter: true


# Подписка на услуги
ServiceSubscription:
  actAs: [Timestampable]
  tableName: billing_subscriptions
  columns:
    id:                     { type: integer(4),    unsigned: true, primary: true,  autoincrement: true }   # ID подписки
    user_id:                { type: integer(4), unsigned: true, notnull: true }                         # ID пользователя
    service_id:             { type: integer(4),    unsigned: true, notnull: true }                         # ID услуги
    subscribed_till:        { type: timestamp(25), notnull: false }                                     # Срок окончания действия подписки на услугу
  relations:
    User:
      local: user_id
      foreign: id
      type: one
      foreignType: one
      onDelete: CASCADE      # При удалении пользователя удаляется вся информация о его подписках
    Service:
      local: service_id
      foreign: id
      type: one
      foreignType: one
  options:
    symfony:
      form:  true
      filter: true


# Транзакции биллинга
BillingTransaction:
  actAs: [Timestampable]
  tableName: billing_transactions
  columns:
    id:                     { type: integer(4),    unsigned: true, primary: true,  autoincrement: true }   # ID транзакции
    user_id:                { type: integer(4), unsigned: true, notnull: true }                         # ID пользователя
    paysystem:              { type: string(32), notnull: true }                                         # Платежная система
    service_id:             { type: integer(4),    unsigned: true, notnull: true }                         # ID услуги
    subscription_id:        { type: integer(4),    unsigned: true, notnull: true }                         # ID подписки на услугу
    price:                  { type: float,      unsigned: true, notnull: true }                         # Оплачиваемая стоимость услуги
    term:                   { type: integer(4),    unsigned: true, notnull: true }                         # Срок
    total:                  { type: float,      unsigned: true, notnull: true }                         # Суммарная стоимость услуги
    status:                 { type: integer(1), unsigned: true, notnull: true, default: 0 }             # Статус: 0 - платеж не овершен, 1 - принят, 2 - ошибка
    success:                { type: integer(1), unsigned: true, notnull: true, default: 0 }             # Оплачено: 0 - нет, 1 - да
    error_code:             { type: integer(4) }                                                           # Код ошибки
    error_message:          { type: string(64) }                                                        # Сообщение об ошибке
  relations:
    User:
      local: user_id
      foreign: id
      type: one
      foreignType: one
    Service:
      local: service_id
      foreign: id
      type: one
      foreignType: one
    ServiceSubscription:
      local: subscription_id
      foreign: id
      type: one
      foreignType: one
  options:
    symfony:
      form:  true
      filter: true

# Категории (100% - OK)
Category:
  tableName: category
  actAs: [Timestampable, SoftDelete]
  columns:
    id:         { name: cat_id as id,                    type: integer(4), notnull: true, primary: true, autoincrement: true}
    parent_id:  { name: cat_parent as parent_id,         type: integer(4), notnull: true, default: 0 }
    system_id:  { name: system_category_id as system_id, type: integer(4), notnull: true, default: 0}
    user_id:    {                                        type: integer(4), notnull: true, unsigned: true}
    name:       { name: cat_name as name,                type: varchar(255), notnull: true}
    type:       { type: integer(1), notnull: true, default: 0}
    custom:     { type: integer(1), notnull: true, default: 1} # 1 - Создана пользователем, 0 - системная
  relations:
    User:
      local: user_id
      foreign: id
      type: one
      foreignType: many
      autoComplete: false         # User ничего не узнает


# Системные категории (100% - OK)
SystemCategory:
  tableName: system_categories
  columns:
    id:   { type: integer(4),   notnull: true, unsigned: true, primary: true, autoincrement: true}
    name: { type: varchar(255), notnull: true}
  options:
    symfony:
      form:   false
      filter: false


# Финансовые цели (3/18 - PART)
Target:
  tableName: target
  columns:
    id:          { type: integer, size: 255, notnull: true, unsigned: true, primary: true }
    user_id:     { type: integer, size: 100, notnull: true, unsigned: true }
    done:        { type: boolean, unsigned: true }
  relations:
    User:
      local:        user_id
      foreign:      id
      type:         one
      foreignType:  many
      foreignAlias: Targets      # User->Targets
      onDelete:     CASCADE      # При удалении пользователя удаляются все его цели
  options:
    symfony:
      form:   false
      filter: false


# Виртуальный счет для финансовых целей / транзакции (5/13 - PART)
TargetTransaction:
  tableName: target_bill
  columns:
    id:         { type: integer, size: 255, notnull: true, unsigned: true, primary: true }
    account_id: { type: integer, size: 255, notnull: true, unsigned: true, name: bill_id as account_id }
    target_id:  { type: integer, size: 255, notnull: true, unsigned: true }
    user_id:    { type: integer, size: 100, notnull: true, unsigned: true }
    money:      { type: decimal, size: 10,  notnull: true, scale: 2}
  relations:
    Target:
      local:        target_id
      foreign:      id
      type:         one
      foreignType:  many
      foreignAlias: Transactions       # Target->Transactions
    Account:
      local:        account_id
      foreign:      id
      type:         one
      foreignType:  many
      foreignAlias: TargetTransactions # Account->TargetTransactions
    User:
      local:        user_id
      foreign:      id
      type:         one
      foreignType:  many
      foreignAlias: TargetTransactions # User->TargetTransactions
      onDelete:     CASCADE            # При удалении пользователя удаляется все
  options:
    symfony:
      form:   false
      filter: false

# Категория бюджета (6/10 - PART)
# Пропущено:
#   - currency
#   - date_end
#   - dt_create
#   - dt_update
BudgetCategory:
  tableName: budget
  columns:
    key:         { type: string(50), notnull: true, primary: true }
    user_id:     { type: integer(4), notnull: true }
    category_id: { name: category as category_id, type: integer(4), notnull: true}
    drain:       { type: integer(1), notnull: true }
    amount:      { type: 'decimal(20, 2)', notnull: true }
    date_start:  { type: date, notnull: true }
  relations:
    User:
      local:        user_id
      foreign:      id
      type:         one
      foreignType:  many
      autoComplete: false         # User ничего не узнает
  options:
    symfony:
      form:   false
      filter: false
