<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/Helper/Money.php';

    /**
     * Test class for Helper_Money.
     * Generated by PHPUnit on 2010-03-05 at 11:49:36.
     */
    class Helper_MoneyTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var Helper_Money
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new Helper_Money;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testFormat().
         */
        public function testFormat ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
