<?php
    require_once 'PHPUnit/Framework.php';

    require_once dirname ( __FILE__ ) . '/../../../../classes/_Core/ObjectWatcher.php';

    /**
     * Test class for _Core_ObjectWatcher.
     * Generated by PHPUnit on 2010-03-05 at 11:49:30.
     */
    class _Core_ObjectWatcherTest extends PHPUnit_Framework_TestCase
    {

        /**
         * @var _Core_ObjectWatcher
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp ()
        {
            $this->object = new _Core_ObjectWatcher;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown ()
        {

        }

        /**
         * @todo Implement testGetInstance().
         */
        public function testGetInstance ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testAddDirty().
         */
        public function testAddDirty ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testAddDeleted().
         */
        public function testAddDeleted ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }

        /**
         * @todo Implement testPerformOperations().
         */
        public function testPerformOperations ()
        {
            // Remove the following lines when you implement this test.
            $this->markTestIncomplete (
                    'This test has not been implemented yet.'
            );
        }
    }

?>
