<?php
/**
 * myTahometerConfigHandler
 */
class myTahometerConfigHandler extends sfYamlConfigHandler
{
    /**
     * Execute
     *
     * @param   mixed   $configFiles
     * @return  string
     */
    public function execute($configFiles)
    {
        // Parse yaml config files
        $configs = self::parseYamls($configFiles);
        if (!count($configs) >= 5) {
            throw new sfConfigurationException('Error while parsing Tahometers configuration.');
        }
        $data = array();
        $data[] = "\$tahometerConfig = array();\n";

        $realTahometerNames = array('Money', 'Budget', 'Loans', 'Difference', 'Total');

        foreach ($configs as $tahometerName => $settings) {
            if (!in_array($tahometerName, $realTahometerNames)) {
                throw new sfConfigurationException(sprintf('Tahometers configuration: unknown Tahometer %s', $tahometerName));
            }
            $data[] = "\$tahometerConfig['" . $tahometerName . "'] = " . var_export($settings, true) . ";";
        }

        // compile data
        $retval = sprintf("<?php\n" .
        "// auto-generated by %s\n" .
        "// @author Svel <svel.sontz@gmail.com>\n" .
        "// @see https://easyfinance.ru\n" .
        "// date: %s\n%s\n", __CLASS__, date('Y-m-d H:i:s'), implode("\n", $data));

        return $retval;
    }

}
