<?php

/**
 * ServiceSubscription
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    EasyFinance
 * @subpackage model
 * @author     EasyFinance
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
class ServiceSubscription extends BaseServiceSubscription
{
   public function getServiceName()
    {
        return $this->getService()->getName();
    }

    public function getUserName()
    {
        return $this->getUser()->getUserName();
    }
}
